import type { Metadata } from "next";
import "./myreset.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
        }}
      >
        <Header></Header>
        <main
          style={{
            flex: "1",
            minHeight: "100vh",
          }}
        >
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
